// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// 商品名の自動補完（Amazon検索やサイト内検索に対応）
import Autocomplete from "stimulus-autocomplete"
application.register("autocomplete", Autocomplete)

// 手放せるものフォーム追加
import ReleasableItemsController from "./releasable_items_controller"
application.register("releasable-items", ReleasableItemsController)

// 画像プレビューの表示
import ImagePreviewController from "./image_preview_controller";
application.register("image-preview", ImagePreviewController);

// 商品検索フォーム（Amazon / サイト内）の表示切り替え
import SearchToggleController from "./search_toggle_controller"
application.register("search-toggle", SearchToggleController)

// レビュー内容にテンプレート文を挿入できるボタン操作を提供
import TemplateController from "./template_controller"
application.register("template", TemplateController)

// テキストエリアのサイズを入力内容に応じて自動調整
import AutosizeController from "./autosize_controller"
application.register("autosize", AutosizeController)