// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosizeController from "./autosize_controller"
application.register("autosize", AutosizeController)

import FormToggleController from "./form_toggle_controller"
application.register("form-toggle", FormToggleController)

import ImageGalleryController from "./image_gallery_controller"
application.register("image-gallery", ImageGalleryController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ReleasableItemsController from "./releasable_items_controller"
application.register("releasable-items", ReleasableItemsController)

import SearchToggleController from "./search_toggle_controller"
application.register("search-toggle", SearchToggleController)

import TemplateController from "./template_controller"
application.register("template", TemplateController)
